#!/usr/bin/env bash
#This script is displaying "best school", "bad luck", and "good luck", using while, if, elif and else statement

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
       echo "Best School"
    fi
    ((i++))
done
