#!/usr/bin/env bash
#write a bash script that displays numbers from 1 to 20 and :

#displays 4 and the bad luck from china for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

i=1

while [ $i -le 20 ]
do
    echo "$i"
    case $i in
        "4") echo "bad luck from china";;
        "9") echo "bad luck from japan";;
        "17") echo "bad luck from italy";;
    esac
    ((i++))
done
