#!/usr/bin/env bash
#This script displays the time for 12 hours anf 59 minutes

#display hours from 0 to 12
#displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        (( minute++ ))
    done
    (( hour++ ))
done
